version: "3.9"

services:
  database:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blog_master
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - database
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1

  wordpress:
    image: wordpress:6.0.2-php8.0-apache
    depends_on:
      - database
      - ./wordpress:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    ports:
      - "6052:80"
    environment:
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=blog_master

volumes:
  db_data: {}
